More fixes to1.18 (#7679)
* Avoid declaration of StatArray with unknown dimension (#7664)

See PowerSystems.Examples.AC3ph.Precalculation.Z_matrixEqCirc0

./OMCppPowerSystems_cpp_PowerSystems.Examples.AC3ph.Precalculation.Z_matrixEqCirc0Initialize.cpp:198:31:
 note: in instantiation of template class 'StatArrayDim1<double, 18446744073709551615, false>' requested here
     StatArrayDim1<double, -1> tmp3;

* Fix AssertionLevel (#7665)

- Swap the order of warning and error in AssertionLevel so they're the
  same order as in the specification.

* Extend Cpp template expTypeFromExpFlag according to C version (#7658)

In particular add TSUB and RSUB.

See ModelicaTest.Math.TestMatrices2:
./OMCppModelicaTest_trunk_cpp_ModelicaTest.Math.TestMatrices2Functions.cpp:4729:9:
 error: unknown type name 'expTypeFromExpFlag'
 ERROR:expTypeFromExpFlag Modelica.Math.Matrices.realSchur(A1)[1]  tmp557;

* Updated documentation of --linkType (#7659)

* Don't consider variability when filtering elements

  - Fixes the immediate issue in #7660.
    The model still does not compile but it is now due to an undefined
    function ``data_of_boolean_f77_array`

  - We were checking `variability` as well when what we actually interested
    in was just the `direction` of the element.

    It is an unfortunate mixup in terminology.

* Fix editing of legend titles (#7670)

Fixes #7627

* Clean up SimCode a bit (#7668)

- Modernise some parts of SimCode to make it easier to see what's going
  on in SimCode.addVarToArrayIndexMapping.

* Distinguish array slice of size 1 from reduction (#7675)

See PowerSystems.Examples.AC3ph.Precalculation.TransDatFromEqCirc

* Updated libraries
* libraries ac8d5d4...0f47ccf (1):
  > Bump libraries

* Improve treatment of unknown dimensions in Cpp runtime (#7677)

See ModelicaTest.Math.TestMatrices3 (MSL 4.0.0)
ERROR  : init  : SimManager: Could not initialize system
ERROR  : init  : SimManager: std::bad_alloc

Co-authored-by: rfranke <rfranke@users.noreply.github.com>
Co-authored-by: perost <perost86@gmail.com>
Co-authored-by: Francesco Casella <francesco.casella@polimi.it>
Co-authored-by: Mahder Gebremedhin <mahder.gebremedhin@liu.se>
Co-authored-by: Adeel Asghar <adeel.asghar@liu.se>
Co-authored-by: hudson <openmodelica@ida.liu.se>