- support noretcall in when equation, add example but still not work because of undefined reference to `Modelica_Utilities_Streams_print'
git-svn-id: https://openmodelica.org/svn/OpenModelica/trunk@13351 f25d12d1-65f4-0310-ae8a-bbce733d8d8e