[FMI] Remove spaces around '=' for canRunAsynchronuosly attribute
While the XML specification allows spaces around the equal sign in
attributes it's common convention to omit them for
readability/consistency/file size.

Also some consumers might be strict about it, e.g. fmi-sim from the
rust-fmi project throws an error because of it:

> fmi-sim --model model.fmu co-simulation
> Error: unknown field "canRunAsynchronuously =" in element "CoSimulation

Remove the spaces around '=' to be consistent with all other attributes

Signed-off-by: Marvin Schmidt <marvin.schmidt@embeff.com>